name: automerge
on:
  workflow_dispatch:
  pull_request_target:
    types:
      - opened
  pull_request:
    types:
      - opened
      - labeled
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
      - name: checkout
      - uses: actions/checkout@v4
      
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""
          MERGE_FILTER_AUTHOR: "pull[bot]"
          MERGE_DELETE_BRANCH: "true"
          UPDATE_LABELS: ""
          LOG: "DEBUG"
